[versions]
loom = "1.7.+"

minotaur = "2.8.+"
cursegradle = "2.+"
github_release = "2.+"
machete = "2.+"

minecraft = "1.21"
quilt_mappings = "5"
fabric_loader = "0.15.11"
fabric_api = "0.100.1+1.21"
yacl = "3.5.0+1.21-fabric"
mod_menu = "11.0.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
